export const GROUPS = [
  {
    id: "entities",
    label: "Entities & Actors",
    accent: "#2F6FED",
    tint: "#EEF3FE",
    x: -200,
    y: -40,
    width: 750,
    height: 480,
  },
  {
    id: "data",
    label: "Data & Algorithmic Flow",
    accent: "#7C4FE0",
    tint: "#F3EEFC",
    x: 430,
    y: -40,
    width: 770,
    height: 780,
  },
  {
    id: "governance",
    label: "Governance & Institutional Actions",
    accent: "#DB8A21",
    tint: "#FDF3E4",
    x: 1220,
    y: -40,
    width: 320,
    height: 570,
  },
  {
    id: "consequence",
    label: "Consequence, Evidence & Responsibility",
    accent: "#0D9488",
    tint: "#E6FBF8",
    x: 1580,
    y: -40,
    width: 320,
    height: 1010,
  },
];

// icon key maps to an entry in Icons.jsx
export const nodes = [
  {
    id: "hft",
    group: "consequence",
    icon: "group",
    title: "Houston Federation of Teachers (HFT)",
    subtitle: "Filed Texas Public Information Act request",
    x: 1600,
    y: 0,
    kind: "Institution / Organization",
    detail: {
      Type: "Institution / Organization",
      Action: "Submitted Public Information Act request regarding EVAAS scores",
      "Source pages": "22",
    },
  },
  {
    id: "observation",
    group: "consequence",
    icon: "eye",
    title: "Classroom Observation Process",
    subtitle: "Ratings aligned with EVAAS",
    x: 1600,
    y: 160,
    kind: "Governance Condition",
    detail: {
      Type: "Governance Condition",
      Role: "Pressure on administrators to align ratings with EVAAS",
      "Source pages": "20–21",
    },
  },
  {
    id: "growth_plan",
    group: "consequence",
    icon: "flag",
    title: "Growth Plan",
    subtitle: "Placed on Daniel Santos, Fall 2013",
    x: 1600,
    y: 320,
    kind: "Consequence",
    detail: {
      Type: "Consequence",
      "Target Person": "Daniel Santos",
      "Source pages": "16, 21",
    },
  },
  {
    id: "hisd_admin",
    group: "consequence",
    icon: "question",
    title: "Unidentified HISD Administrator",
    subtitle: "Growth-plan approval — unresolved",
    x: 1600,
    y: 480,
    kind: "Responsibility Gap",
    gapNode: true,
    detail: {
      Type: "Responsibility Gap",
      Issue: "Complaint does not identify who approved growth plan",
      "Source pages": "16, 21",
    },
  },
  {
    id: "reviewer",
    group: "consequence",
    icon: "question",
    title: "Unidentified Reviewer / Oversight Actor",
    subtitle: "Independent review — unresolved",
    x: 1600,
    y: 640,
    kind: "Responsibility Gap",
    gapNode: true,
    detail: {
      Type: "Responsibility Gap",
      Issue: "Complaint does not establish independent review authority",
      "Source pages": "20–23",
    },
  },

  ////

  {
    id: "daniel",
    group: "entities",
    icon: "person",
    title: "Daniel Santos",
    subtitle: "Teacher (HISD)",
    x: 0,
    y: 60,
    kind: "Person / Actor",
    detail: {
      Type: "Person / Actor",
      Role: "6th grade social studies teacher",
      "Employed by": "Houston Independent School District",
      "Taught at": "Jackson Middle School",
      "Source pages": "2",
    },
  },
  {
    id: "hisd",
    group: "entities",
    icon: "institution",
    title: "Houston Independent School District (HISD)",
    subtitle: "District",
    x: 280,
    y: 60,
    kind: "Institution / Organization",
    detail: {
      Type: "Institution / Organization",
      Role: "School district; employer of Daniel Santos",
      "Contracted with": "SAS (for EVAAS)",
      "Provided data to": "Stanford/Aprenda vendor, SAS",
      Used: "EVAAS score in appraisal",
      "Source pages": "2, 9, 21–24",
    },
  },
  {
    id: "jackson",
    group: "entities",
    icon: "school",
    title: "Jackson Middle School",
    subtitle: "Middle School (6th Grade Social Studies)",
    x: 0,
    y: 280,
    kind: "School / Education",
    detail: {
      Type: "School / Education",
      "Part of": "Houston Independent School District",
      "Taught by": "Daniel Santos",
      "Source pages": "2",
    },
  },
  {
    id: "stanford",
    group: "data",
    icon: "assessment",
    title: "Stanford / Aprenda",
    subtitle: "Social Studies Assessment (used when STAAR not available)",
    x: 600,
    y: 0,
    kind: "Assessment / Report",
    detail: {
      Type: "Assessment / Report",
      "Used by": "HISD",
      Condition: "Alleged misalignment with required curriculum",
      "Source pages": "9, 23–24",
    },
    flag: "Alleged misalignment with required curriculum",
  },
  {
    id: "testdata",
    group: "data",
    icon: "data",
    title: "Student Test Data",
    subtitle: "Prior & current standardized tests",
    x: 920,
    y: 0,
    kind: "Data / Information",
    detail: {
      Type: "Data / Information",
      Contains: "Prior & current standardized test scores",
      "Sent for analysis to": "SAS",
      "Source pages": "13–15, 21–22",
    },
  },
  {
    id: "evaas_report",
    group: "data",
    icon: "output",
    title: "EVAAS Score / Teacher Value-Added Report",
    subtitle: "Provided to HISD",
    x: 600,
    y: 250,
    kind: "Algorithmic Output",
    detail: {
      Type: "Algorithmic Output",
      "Generated by": "SAS",
      "Input from": "Student Test Data (prior & current performance)",
      "Provided to": "HISD",
      "Used in": "Teacher Appraisal System & high-stakes decisions",
      "Related to": 'Daniel Santos (deemed "least effective")',
      "Source pages": "13–15, 21–22, 24",
      "Responsibility significance":
        "Links algorithmic analysis to institutional decision-making and employment consequences.",
      "Evidence / gap":
        "Exact execution details for Santos's score and his specific EVAAS report are not available in the complaint.",
    },
    highlight: true,
  },
  {
    id: "sas",
    group: "data",
    icon: "gear",
    title: "SAS",
    subtitle: "Statistical Analysis Service",
    x: 940,
    y: 250,
    kind: "External Service / System",
    detail: {
      Type: "External Service / System",
      "Contracted by": "HISD",
      "Received data from": "HISD (student test data)",
      Generated: "EVAAS Score / Teacher Value-Added Report",
      "Source pages": "13–15, 21–22",
    },
  },
  {
    id: "daniel_report",
    group: "data",
    icon: "person",
    title: "Daniel Santos",
    subtitle: 'Value-Added Report — "Least Effective"',
    x: 600,
    y: 500,
    kind: "Person / Actor",
    detail: {
      Type: "Person / Actor",
      "Reported result for": "EVAAS Score / Teacher Value-Added Report",
      Outcome: '"Least Effective" designation',
      "Used in evaluation of": "Teacher appraisal & high-stakes decisions",
      "Source pages": "16, 21",
    },
    pink: true,
  },
  {
    id: "hisd_contract",
    group: "governance",
    icon: "institution",
    title: "HISD",
    subtitle: "Contracted with SAS (for EVAAS)",
    x: 1260,
    y: 0,
    kind: "Institution / Organization",
    detail: {
      Type: "Institution / Organization",
      "Contracted with": "SAS",
      Purpose: "Production of EVAAS scores",
      "Source pages": "21–22",
    },
  },
  {
    id: "evaas_gov",
    group: "governance",
    icon: "chart",
    title: "EVAAS",
    subtitle: "In teacher appraisal system & high-stakes decisions",
    x: 1260,
    y: 250,
    kind: "Data / Information",
    detail: {
      Type: "Data / Information",
      "Derived from": "Student Test Data",
      "Used by": "HISD",
      "Used in evaluation of": "Daniel Santos",
      Condition: "Preceded placement on growth plan",
      "Source pages": "15–16, 21",
    },
  },

  // Add these to the `nodes` array

  {
    id: "growth_plan_detail",
    group: "consequence",
    icon: "flag",
    title: "Growth Plan Terms",
    subtitle: "Additional training, PD & tasks",
    x: 1600,
    y: 400, // place between growth_plan and hisd_admin
    kind: "Consequence Detail",
    detail: {
      Type: "Consequence Detail",
      Description:
        "Prescriptive plans requiring additional training, professional development, and tasks",
      "Target Person": "Daniel Santos",
      "Source pages": "16",
    },
  },

  {
    id: "partial_info",
    group: "consequence",
    icon: "data",
    title: "Partial EVAAS Information",
    subtitle: "Provided by HISD to HFT",
    x: 1600,
    y: 80,
    kind: "Evidence / Transparency",
    detail: {
      Type: "Evidence / Transparency",
      Action:
        "HISD provided some general information concerning the EVAAS process",
      Characterization: "Limited",
      "Source pages": "22",
    },
  },

  {
    id: "withheld_info",
    group: "consequence",
    icon: "warning",
    title: "Withheld Methodology & Source Code",
    subtitle: "Source code, decision rules, statistical controls",
    x: 1600,
    y: 240,
    kind: "Evidence / Transparency Gap",
    gapNode: true,
    detail: {
      Type: "Evidence / Transparency Gap",
      Issue:
        "HISD did not provide source code, decision rules, statistical controls, or information sufficient to reproduce the analysis",
      "Source pages": "22–23",
    },
  },

  {
    id: "proprietary_control",
    group: "data",
    icon: "gear",
    title: "EVAAS Methodology (Proprietary)",
    subtitle: "Neither HISD nor others had access",
    x: 940,
    y: 420,
    kind: "External Control / Evidence Gap",
    gapNode: true,
    detail: {
      Type: "External Control / Evidence Gap",
      Issue:
        "HISD represented the SAS EVAAS analysis as proprietary; neither HISD nor others had access to the calculations",
      "Source pages": "22",
    },
  },

  {
    id: "responsibility_sas",
    group: "consequence",
    icon: "gear",
    title: "SAS — Responsibility Candidate",
    subtitle: "Generation of algorithmic output",
    x: 1600,
    y: 800,
    kind: "Responsibility Finding",
    detail: {
      Type: "Responsibility Finding",
      Connection: "Statistical generation of the EVAAS teacher-specific result",
      Limitation:
        "Does not by itself establish responsibility for HISD’s employment decision",
      "Source pages": "13–15, 21–22",
    },
  },

  {
    id: "responsibility_hisd",
    group: "consequence",
    icon: "institution",
    title: "HISD — Responsibility Candidate",
    subtitle: "Authority, control & consequence",
    x: 1600,
    y: 920,
    kind: "Responsibility Finding",
    detail: {
      Type: "Responsibility Finding",
      Connection:
        "Supplied data, adopted EVAAS for appraisal, decided how results would be used, imposed employment consequences",
      "Source pages": "15–16, 20–24",
    },
  },
];

export const edges = [
  // ── 1. Consequential Conduct ─────────────────────────────────────────────

  {
    id: "e17",
    n: 17,
    source: "hisd_contract",
    target: "observation",
    from: "hisd_contract",
    to: "observation",
    label: "USED",
    pages: "p.20–21",
    kind: "direct",
  },
  {
    id: "e18",
    n: 18,
    source: "daniel",
    target: "growth_plan",
    from: "daniel",
    to: "growth_plan",
    label: "PLACED_ON",
    pages: "p.16, 21",
    kind: "direct",
  },
  {
    id: "e19",
    n: 19,
    source: "hft",
    target: "hisd",
    from: "hft",
    to: "hisd",
    label: "REQUESTED_FROM",
    pages: "p.22",
    kind: "direct",
  },
  {
    id: "e20",
    n: 20,
    source: "hisd_admin",
    target: "growth_plan",
    from: "hisd_admin",
    to: "growth_plan",
    label: "TRACE: unresolved",
    pages: "p.16, 21",
    kind: "unresolved",
  },
  {
    id: "e21",
    n: 21,
    source: "reviewer",
    target: "daniel_report",
    from: "reviewer",
    to: "daniel_report",
    label: "TRACE: unresolved",
    pages: "p.20–23",
    kind: "unresolved",
  },

  //////////

  {
    id: "e1",
    n: 1,
    source: "daniel",
    target: "hisd",
    from: "daniel",
    to: "hisd",
    label: "EMPLOYED_BY",
    pages: "p.2",
    kind: "direct",
  },
  {
    id: "e2",
    n: 2,
    source: "daniel",
    target: "jackson",
    from: "daniel",
    to: "jackson",
    label: "TAUGHT_AT",
    pages: "p.2",
    kind: "direct",
  },

  // ── 3. Institutional Structure ───────────────────────────────────────────
  {
    id: "e3",
    n: 3,
    source: "jackson",
    target: "hisd",
    from: "jackson",
    to: "hisd",
    label: "PART_OF",
    pages: "p.2",
    kind: "direct",
  },

  // ── 4. Algorithmic Input ─────────────────────────────────────────────────
  {
    id: "e4",
    n: 4,
    source: "hisd",
    target: "stanford",
    from: "hisd",
    to: "stanford",
    label: "USED",
    pages: "p.9, 23–24",
    kind: "direct",
    note: "Stanford/Aprenda assessment; STAAR not available for subject/grade",
  },

  // ── 5. Governance Act / Input Condition ──────────────────────────────────
  {
    id: "e5",
    n: 5,
    source: "hisd",
    target: "stanford",
    from: "hisd",
    to: "stanford",
    label: "USED",
    pages: "p.23–24",
    kind: "condition",
    note: "Alleged misalignment with required curriculum",
    chipOnly: true,
  },

  // ── 6. Algorithmic Input — Data Transfer ─────────────────────────────────
  {
    id: "e6",
    n: 6,
    source: "hisd",
    target: "sas",
    from: "hisd",
    to: "sas",
    label: "PROVIDED_DATA_TO",
    pages: "p.21–22",
    kind: "direct",
  },

  // ── 7. Governance Act — Contract ─────────────────────────────────────────
  {
    id: "e7",
    n: 7,
    source: "hisd",
    target: "hisd_contract",
    from: "hisd",
    to: "hisd_contract",
    label: "CONTRACTED_WITH",
    pages: "p.21–22",
    kind: "direct",
    note: "HISD contracted SAS to generate EVAAS scores",
  },

  // ── 8. Algorithmic Conduct — Data Sent ───────────────────────────────────
  {
    id: "e8",
    n: 8,
    source: "testdata",
    target: "sas",
    from: "testdata",
    to: "sas",
    label: "SENT_FOR_ANALYSIS",
    pages: "p.13–15",
    kind: "direct",
  },

  // ── 9. Algorithmic Conduct — Score Generation ────────────────────
  {
    id: "e9",
    n: 9,
    source: "sas",
    target: "evaas_report",
    from: "sas",
    to: "evaas_report",
    label: "GENERATED",
    pages: "p.13–15, 21–22",
    kind: "direct",
  },

  // ── 10. Algorithmic Conduct — Derivation ─────────────────────────────────
  {
    id: "e10",
    n: 10,
    source: "evaas_report",
    target: "testdata",
    from: "evaas_report",
    to: "testdata",
    label: "DERIVED_FROM",
    pages: "p.13–15",
    kind: "direct",
  },

  // ── 11. Authority — HISD uses EVAAS in appraisal ────────────────────────
  {
    id: "e11",
    n: 11,
    source: "hisd_contract",
    target: "evaas_gov",
    from: "hisd_contract",
    to: "evaas_gov",
    label: "USED",
    pages: "p.15–16",
    kind: "direct",
    note: "HISD used EVAAS student-performance measures in appraisal & high-stakes decisions",
  },

  // ── 12. Authority — Score used in evaluation ─────────────────────────────
  {
    id: "e12",
    n: 12,
    source: "evaas_gov",
    target: "daniel_report",
    from: "evaas_gov",
    to: "daniel_report",
    label: "USED_IN_EVALUATION_OF",
    pages: "p.16, 21",
    kind: "direct",
  },

  // ── 13. Control — HISD receives and uses EVAAS results ───────────────────
  {
    id: "e13",
    n: 13,
    source: "evaas_report",
    target: "daniel_report",
    from: "evaas_report",
    to: "daniel_report",
    label: "REPORTED_RESULT_FOR",
    pages: "p.24",
    kind: "direct",
  },

  // ── 14. Control — SAS statistical generation (TRACE) ─────────────────────
  {
    id: "e14",
    n: 14,
    source: "sas",
    target: "evaas_report",
    from: "sas",
    to: "evaas_report",
    label: "GENERATED",
    pages: "p.21–22",
    kind: "trace",
    note: "SAS controlled the statistical generation process; HISD did not independently verify",
    unnumbered: false,
  },

  // ── 15. Control / Evidence Gap — HISD reliance without verification ───────
  {
    id: "e15",
    n: 15,
    source: "hisd_contract",
    target: "sas",
    from: "hisd_contract",
    to: "sas",
    label: "USED_WITHOUT_VERIFICATION",
    pages: "p.21–22",
    kind: "gap",
    note: "HISD did not independently verify SAS's statistical analysis",
  },

  // ── 16. Governance Act — Low score triggers employment consequence ─────────
  {
    id: "e16",
    n: 16,
    source: "evaas_gov",
    target: "evaas_report",
    from: "evaas_gov",
    to: "evaas_report",
    label: "USED_AS_EMPLOYMENT_MEASURE",
    pages: "p.15–16",
    kind: "trace",
    note: "Low EVAAS scores used to trigger sanctions, growth plans, and employment consequences",
  },

  // Add these to the `edges` array

  // Row 19 – what the Growth Plan actually meant
  {
    id: "e19b",
    n: 19,
    source: "growth_plan",
    target: "growth_plan_detail",
    from: "growth_plan",
    to: "growth_plan_detail",
    label: "MEANS",
    pages: "p.16",
    kind: "direct",
  },

  // Rows 21–22 – transparency path
  {
    id: "e21a",
    n: 21,
    source: "hisd",
    target: "partial_info",
    from: "hisd",
    to: "partial_info",
    label: "PROVIDED_TO",
    pages: "p.22",
    kind: "direct",
    note: "Some general information concerning the EVAAS process",
  },
  {
    id: "e21b",
    n: 21,
    source: "partial_info",
    target: "hft",
    from: "partial_info",
    to: "hft",
    label: "RECEIVED_BY",
    pages: "p.22",
    kind: "direct",
  },

  // Row 22 – withholding
  {
    id: "e22",
    n: 22,
    source: "hisd",
    target: "withheld_info",
    from: "hisd",
    to: "withheld_info",
    label: "WITHHELD_FROM",
    pages: "p.22–23",
    kind: "gap",
    note: "Source code, decision rules, statistical controls not provided",
  },
  {
    id: "e22b",
    n: 22,
    source: "withheld_info",
    target: "hft",
    from: "withheld_info",
    to: "hft",
    label: "NOT_AVAILABLE_TO",
    pages: "p.22–23",
    kind: "gap",
  },

  // Row 23 – proprietary control
  {
    id: "e23",
    n: 23,
    source: "sas",
    target: "proprietary_control",
    from: "sas",
    to: "proprietary_control",
    label: "CONTROLS",
    pages: "p.22",
    kind: "gap",
    note: "Methodology treated as proprietary; HISD claimed neither it nor others had access",
  },
  {
    id: "e23b",
    n: 23,
    source: "hisd",
    target: "proprietary_control",
    from: "hisd",
    to: "proprietary_control",
    label: "NO_ACCESS",
    pages: "p.22",
    kind: "gap",
  },

  // Row 24 – SAS responsibility finding
  {
    id: "e24",
    n: 24,
    source: "sas",
    target: "responsibility_sas",
    from: "sas",
    to: "responsibility_sas",
    label: "TRACE: Responsibility / Control candidate",
    pages: "p.13–15, 21–22",
    kind: "trace",
  },

  // Row 25 – HISD responsibility finding
  {
    id: "e25",
    n: 25,
    source: "hisd",
    target: "responsibility_hisd",
    from: "hisd",
    to: "responsibility_hisd",
    label: "TRACE: Authority / Control / Responsibility candidate",
    pages: "p.15–16, 20–24",
    kind: "trace",
  },

  // Strengthen the existing observation pressure edge (row 17)
  // You can keep e17 or replace its note with:
  {
    id: "e17",
    n: 17,
    source: "hisd_contract",
    target: "observation",
    from: "hisd_contract",
    to: "observation",
    label: "DIRECTED / PRESSURED",
    pages: "p.20–21",
    kind: "direct",
    note: "HISD directed or pressured campus administrators to align instructional-practice ratings with low EVAAS outcomes",
  },
];

export const legend = [
  { icon: "person", label: "Person / Actor" },
  { icon: "institution", label: "Institution / Organization" },
  { icon: "school", label: "School / Education" },
  { icon: "assessment", label: "Assessment / Report" },
  { icon: "gear", label: "External Service / System" },
  { icon: "data", label: "Data / Information" },
  { icon: "flag", label: "Consequence" },
  { icon: "warning", label: "Evidence / Transparency Gap" },
  { icon: "question", label: "Responsibility Gap" },
  { icon: "eye", label: "Governance Condition" },
];
